providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = "20"
YOUTUBE_DL_SKIP_PYTHON_CHECK = "1"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_20", "bun", "python3", "ffmpeg", "yt-dlp", "fontconfig", "dejavu_fonts"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
